### ISSUE TITLE
MarkDuplicates memory requirement is malformed

### ISSUE THREAD

**Issue by szilvajuhos** [SciLifeLab/CAW#102]
Oct-22 00:05:16.091 [pool-2-thread-1] DEBUG nextflow.executor.GridTaskHandler - Launching process > MarkDuplicates (ST438T__1) -- work folder: /pica/v9/b2011185_nobackup/private/wabi/CAW_ascat/CAW/work/89/e355373bd5e41d2a8bafe8ca59230d
Oct-22 00:05:16.096 [pool-2-thread-1] ERROR nextflow.processor.TaskProcessor - Unable to re-submit task `MarkDuplicates (ST438T__1)`
Oct-22 00:05:16.098 [pool-2-thread-1] DEBUG nextflow.Session - Session aborted -- Cause: Not a valid 'memory' value in process definition: 32.G32.G

**Comment by szilvajuhos** [comment]
See https://github.com/SciLifeLab/CAW/commit/4c55acab9e5851c8aeb863df8f81334b26f98564 
Seems it is a typo

**Comment by szilvajuhos** [comment]
@malinlarsson could you please fix the config file (milou.config I guess) by adding an extra G and try a -resume, to see whether it works?

**Comment by malinlarsson** [comment]
Sure! I fixed the code to singleCPUMem  = '32.GB'
and restarted with -resume. 
The nextflow run jumped directly to MarkDuplicates, so the -resume worked.

**Comment by szilvajuhos** [comment]
Great, seems the Manta fix also working, so I will merge them tomorrow.

**Comment by szilvajuhos** [comment]
Using the master branch it should be OK, it is the config/milou-github.config file that should be used as default.

**Comment by malinlarsson** [comment]
Hi!

I checked the new run that I started yesterday and it failed again on the MarkDuplicates step.

This is the error message from the .nextflow.log file: 
Oct-25 03:23:04.040 [pool-2-thread-1] ERROR nextflow.processor.TaskProcessor - Unable to re-submit task `MarkDuplicates (ST438T__1)`
Oct-25 03:23:04.041 [pool-2-thread-1] DEBUG nextflow.Session - Session aborted -- Cause: Not a valid 'memory' value in process definition: 32.GB32.GB

I dont understand why it the memory definition is repeated two times? (32.GB32.GB) That seems to be the problem. 

The job is started, but then canceled. Here is the output from "finshedjobinfo": 
2016-10-25 03:22:24 jobid=8923377 jobstate=CANCELLED username=malin account=b2015110 nodes=m64 procs=4 partition=core qos=normal jobname=nf-MarkDuplicates_(ST438T__1) maxmemory_in_GiB=32.0 maxmemory_node=m64 timelimit=4-04:00:00 submit_time=2016-10-24T19:11:56 start_time=2016-10-25T01:12:53 end_time=2016-10-25T03:22:24 runtime=02:09:31 margin=4-01:50:29 queuetime=06:00:57

Also, I dont understand why it wasn't a problem for the normal sample, that one worked.

**Comment by ansluk** [comment]
Hi,

Just guessing, but do the 32.GB32GB output come from the second task.attempt? It looks like multiplying a string by two. Should there be single quotes around mem statements in the config file?

mvh
Anders Lundmark
________________________________

**Comment by J35P312** [comment]
Aloha!
That seems to be correct, the trick seems to be that you need to state the memory in this way:
memory = 1.GB
i.e with no quotes and the amount of memory and unit separated by a dot. This is shown at this site:
https://www.nextflow.io/blog/2016/error-recovery-and-automatic-resources-management.html
Here's a small test script that requests more memory upon each try

singleCPUMem=1.GB

process retryIfFail {
   errorStrategy 'retry'
   memory {  singleCPUMem* task.attempt }
   maxRetries 10
   maxErrors '-1'
   script:
   """
   bwa -mem I_do_not_exist.fa
   """ 
}

Good night!
//Jesper

**Comment by szilvajuhos** [comment]
Thanks, I have tested on a downsampled dataset so never had to retry. So, @malinlarsson if you just write 64.GB for the time being as a quick fix that should do. I will go through the test at this afternoon (though @ansluk or @J35P312 feel free to overtake ;)
Meanwhile the downsampled ASCAT run works fine on milou, alleleCount completed, convertAlleleCounts in progress (pending in the queue).
