### ISSUE TITLE
Correct Manta issue

### ISSUE THREAD

**Issue by MaxUlysse** [SciLifeLab/CAW#126]
Error is:
> Reference fasta and 'Normal' BAM/CRAM file conflict on chromosome: 'hs37d5'

**Comment by MaxUlysse** [comment]
using:
```
mantaRef = '/sw/data/uppnex/ToolBox/ReferenceAssemblies/hg38make/bundle/2.8/b37/MANTA_human_g1k_v37_decoy.fasta'
mantaIndex = '/sw/data/uppnex/ToolBox/ReferenceAssemblies/hg38make/bundle/2.8/b37/MANTA_human_g1k_v37_decoy.fasta.fai'
```
and the Downsampled data

**Comment by MaxUlysse** [comment]
> ```
> Dynamic exception type: N5boost16exception_detail10clone_implIN8illumina6common14LogicExceptionEEE
> std::exception::what: SVbreakend has unknown or invalid chromosome id in candidate sv.
>         local_bam_record: D0ENMACXX111207:1:2104:3567:112276/2 tid:pos:strand 1:162136647:- cigar: 21S80M mate_tid:pos:strand 85:20824988:+
>         remote_bam record: NONE
>         SVCandidate: SVCandidate:
>         isImprecise?: 1
>         fwReads: 0 ; rvReads: 0
>         index candidate:assemblyAlign:assemblySegment: 0:0:0
>         Breakend: GenomeInterval: 1:[162136454,162136647) LEFT_OPEN
>         SVBreakendLowResEvidence: pair: 0 local_pair: 1 cigar: 0 softclip: 0 semialign: 0 shadow: 0 split_align: 0 unknown: 0
> 
>         Breakend: GenomeInterval: 85:[20825089,20825282) RIGHT_OPEN
>         SVBreakendLowResEvidence: pair: 0 local_pair: 0 cigar: 0 softclip: 0 semialign: 0 shadow: 0 split_align: 0 unknown: 0
> 
> 
> 
> : SVbreakend has unknown or invalid chromosome id in candidate sv.
>         local_bam_record: D0ENMACXX111207:1:2104:3567:112276/2 tid:pos:strand 1:162136647:- cigar: 21S80M mate_tid:pos:strand 85:20824988:+
>         remote_bam record: NONE
>         SVCandidate: SVCandidate:
>         isImprecise?: 1
>         fwReads: 0 ; rvReads: 0
>         index candidate:assemblyAlign:assemblySegment: 0:0:0
>         Breakend: GenomeInterval: 1:[162136454,162136647) LEFT_OPEN
>         SVBreakendLowResEvidence: pair: 0 local_pair: 1 cigar: 0 softclip: 0 semialign: 0 shadow: 0 split_align: 0 unknown: 0
> 
>         Breakend: GenomeInterval: 85:[20825089,20825282) RIGHT_OPEN
>         SVBreakendLowResEvidence: pair: 0 local_pair: 0 cigar: 0 softclip: 0 semialign: 0 shadow: 0 split_align: 0 unknown: 0
> ```

**Comment by szilvajuhos** [comment]
Seems NC_007605 was left in the Manta reference. Deleted now, will start a new test.

**Comment by szilvajuhos** [comment]
Seems now works on bianca, @malinlarsson could you please eventually check on milou, or shall I check first?

**Comment by szilvajuhos** [comment]
It works on both milou and bianca: all we have to do is to leave the reference as it is, and do not remove the decoys - easier to simply filter out false calls laters, since manta runtime is about 2-3 hours only.
