### ISSUE TITLE
Validated real datasets

### ISSUE THREAD

**Issue by szilvajuhos** [SciLifeLab/CAW#148]
Data for https://www.ncbi.nlm.nih.gov/pubmed/?term=26647970 is at
https://www.ebi.ac.uk/ega/studies/EGAS00001001539
We have to apply to access at dcc-support@icgc.org ( following 
https://www.ebi.ac.uk/ega/about/access )

The actual related article at:
https://www.nature.com/articles/ncomms10001

We have full data for https://www.ebi.ac.uk/ega/datasets/EGAD00001001859 (medulloblastoma)

**Comment by szilvajuhos** [comment]
No we have Malin, Maxime and me as users also Max as PI. Waiting for @gulfshores (Max) to give a recommendation for an actual authorised person.

**Comment by szilvajuhos** [comment]
Data on irma at: /lupus/home/szilva/ICGC/184_fastq . First we are going to use the HQ_... files since the other ones are 1.3+ quality scored and shorter in general . The expected coverage is still high (300).

**Comment by szilvajuhos** [comment]
First test run: using DKFZ NEB samples, as they are providing ~45X coverage for both normal and tumour, similar to our samples. 

- [ ] preprocessing
- [ ] variant call
- [ ] annotation
- [ ] comparison to Gold Standard

**Comment by MaxUlysse** [comment]
Good news, are the fastqs available somewhere, so that I can begin to plan to use them for #328

**Comment by ewels** [comment]
This is now all complete.

**Comment by elfore** [comment]
I am a student who wants to find some validated datasets to test my method on somatic variant calling, but I can not get access to this data because I can not reach a PI? Could you please release the data for me?

**Comment by szilvajuhos** [comment]
Hej, we can not grant access to the files as it is patient data, and you need a quite a lot of paperwork with signatures from both your PI and Head of Institute to access it: http://icgc.org/index.php?q=daco The actual spreadsheet you are referring to links to the final results of our workflow, being useless from your point of you. It is using the medulloblastoma dataset from this publication: https://www.nature.com/articles/ncomms10001 and hopefully will be a preprint sometimes early next year. 
If you need further help, contact me by email (szilveszter.juhos at scilifelab.se) , cheers:
Szilva

**Comment by elfore** [comment]
@szilvajuhos Thank you for your reply, I think I'd better get some softwares to simulate the validation data. Thank you all the same.
