### ISSUE TITLE
Running without the --project parameter throws an error

### ISSUE THREAD

**Issue by dahlo** [SciLifeLab/CAW#156]
Hi there

I tried to run CAW on my laptop and followed the instructions on how to run the test data set, but i shuts down with the following error message: 

```bash
CAW $ nextflow run main.nf --test
N E X T F L O W  ~  version 0.23.0
Launching `main.nf` [compassionate_wright] - revision: 4a96e771ec
ERROR ~ No UPPMAX project ID found! Use --project <UPPMAX Project ID>

 -- Check '.nextflow.log' file for details
```

Any suggestions on how to run CAW when not being on uppmax?

**Comment by MaxUlysse** [comment]
Hello,
It's quite simple in fact, I advise you to make a new configuration file based on [milou.config](https://github.com/SciLifeLab/CAW/blob/master/configuration/milou.config) and [milou-slurm](https://github.com/SciLifeLab/CAW/blob/master/configuration/milou-slurm.config).
(Which you should because the current ones are made for our UPPMAX clusters).
And include it in the main configuration file [nextflow.config](https://github.com/SciLifeLab/CAW/blob/master/nextflow.config#L31-L46) your own configuration files with your chosen profile name (let's say dahlo)
afterwards, you just need to run:
```nextflow run main.nf -profile dahlo --test```
Don't hesitate if you have any more problems.

**Comment by szilvajuhos** [comment]
Hi,
There is a localhost profile, like
nextflow run main.nf -profile localhost --sample data/tsv/tiny.tsv --steps
preprocessing,MuTect1 --verbose

The configuration/localhost.conf likely needs adjustment,  as it is set to
a big machine.
Modules and reference files also have to be in place,  but I run it on my
laptop frequently,  let me know how it goes:

Szilva

**Comment by dahlo** [comment]
Alright, i'll give the local profiles a go!

Thanks for the help!

**Comment by szilvajuhos** [comment]
What I have is a sort of local mirror
of /sw/data/uppnex/ToolBox/ReferenceAssemblies/hg38make/bundle/2.8/b37/
though not all the 7G, "only" 27G of references and indexes. The largest
beast is dbsnp_138.b37.vcf (can be made smaller for tests), and the
references obviously. The list of files are in the param section
of configuration/localhost.config
Szilva

**Comment by dahlo** [comment]
Hehe, i'm standing in that folder now and have started copying stuff to my computer :) I saw that you had a folder named hg38bundle you use files from, so i tried to run their makefile to get everything i need. Turns out Broad have changed their ftp structure since that script though, but even after correcting the paths, the download speed was only ~400kbps so i figured my dl rate from uppmax would probably be better. Should be done copying in a while.

**Comment by szilvajuhos** [comment]
Shall I zip what I have and put is somewhere temp space?

**Comment by dahlo** [comment]
Oh, that would be nice! I should soon have these files:

```
Mills_and_1000G_gold_standard.indels.b37.vcf
1000G_phase1.indels.b37.vcf
dbsnp_138.b37.vcf
hapmap_3.3.b37.vcf
1000G_omni2.5.b37.vcf
1000G_phase1.snps.high_confidence.b37.vcf
Mills_and_1000G_gold_standard.indels.b37.vcf.idx
1000G_phase1.indels.b37.vcf.idx
dbsnp_138.b37.vcf.idx
hapmap_3.3.b37.vcf.idx
1000G_omni2.5.b37.vcf.idx
1000G_phase1.snps.high_confidence.b37.vcf.idx
```

so if there is anything else i would need to get going that would be really helpful.
