### ISSUE TITLE
Missing dependencies in instructions

### ISSUE THREAD

**Issue by dahlo** [SciLifeLab/CAW#160]
Hello again, i'm just creating issues for the things i notice while trying to run the pipeline. 

There seems to be a couple of dependencies missing in the installation instructions.

- Mutect
- SnpEff
- VarDictJava

**Comment by MaxUlysse** [comment]
Thanks a lot for reporting these issues.
It's quite hard to notice them.

**Comment by MaxUlysse** [comment]
Duplicated with #120
