### ISSUE TITLE
Unable to use custom profile names

### ISSUE THREAD

**Issue by dahlo** [SciLifeLab/CAW#161]
I just copied the configurations/localhost.config to a new name, dahlo.config, and modified it and tried to run it, but it gives me this error:

```bash
$ nextflow run main.nf -profile dahlo --test
N E X T F L O W  ~  version 0.23.0
Launching `main.nf` [reverent_stallman] - revision: 4a96e771ec
Unknown configuration profile: 'dahlo'
```

If i rename dahlo.config to localhost.config it works perfectly though, so it should not be a problem in the file itself.

**Comment by szilvajuhos** [comment]
Hi, to make a profile, first you have to edit the nextflow.config file i.e. like https://github.com/SciLifeLab/CAW/blob/master/nextflow.config , that is at the same place where the main.nf is. You can define the location of the corresponding config files for a profile there.
