### ISSUE TITLE
Strelka fails for relapse

### ISSUE THREAD

**Issue by szilvajuhos** [SciLifeLab/CAW#167]
If we have a normal - tumor - relapse case, Strelka will make only a normal-tumor VCF, no trace of relapse in the final VCF

**Comment by szilvajuhos** [comment]
To try it out have to make a tiny normal-tumor-relapse case first.

**Comment by ansluk** [comment]
Mine are made but not all published (or all published with with the same name, overwriting)
I pull the missing vcf-files from work cache.

**Comment by MaxUlysse** [comment]
@Szilva thanks for reporting the issue, I'm trying a test case right now.

@ansluk Can you please elaborate a little more on your issue ?

**Comment by ansluk** [comment]
In my case Strelka has run for all normal vs tumor, relapse 1 relapse 2 pairs and the resulting vcf files are in the work cache, but I think only files from one comparison are in VariantCalling/Strelka
strelka
     results
          all.somatic.indels.vcf
          all.somatic.snvs.vcf
          passed.somatic.indels.vcf
          passed.somatic.snvs.vcf

**Comment by MaxUlysse** [comment]
Thanks a lot.
I figured out what was causing the problem, trying a fix at the moment.

**Comment by MaxUlysse** [comment]
@ansluk
Issue is fixed, now you should have in `VariantCalling/Strelka`:
- `normalID_tumorID_all_somatic_indels.vcf`
- `normalID_tumorID_all_somatic_snvs.vcf`
- `normalID_tumorID_passed_somatic_indels.vcf`
- `normalID_tumorID_passed_somatic_snvs.vcf`
