### ISSUE TITLE
Recalibration table should be copied to Preprocessing/

### ISSUE THREAD

**Issue by szilvajuhos** [SciLifeLab/CAW#171]
Sometimes RecalibrateBam fails, but we do not have the recalibration table, so we have to re-run CreateRecalibrationTable as well. Saving the recalibration table would save some time as we have to salvage the entries by hand anyway.

**Comment by MaxUlysse** [comment]
Sounds like a good idea.
But my guess is that the -resume option is not working when using scratch ?
