### ISSUE TITLE
Set up maxforks in a clever way

### ISSUE THREAD

**Issue by MaxUlysse** [SciLifeLab/CAW#175]
> maxforks had to be decreased to make sure we are not killing the node with 8 bwas using 16 threads each. In the future it should be set in a more clever way, i.e. for recalibration is should be only 1

**Comment by szilvajuhos** [comment]
#79 also related to this, more or less it is OK  - have to be adjusted for each instance of localhost usage anyway.
There have to be a set for
- [  ] bianca - using slurm for everyting (-profile bianca)
- [  ] bianca node: when using sbatch to launch something on a local node (-profile bianca-node)
- [  ] the same two for milou 
- [  ] ditto for irma
