### ISSUE TITLE
Add extra variant calling calls

### ISSUE THREAD

**Issue by MaxUlysse** [SciLifeLab/CAW#193]
We had T vs N, R vs N.
We now also want R vs T...

**Comment by MaxUlysse** [comment]
Given that we don't have a specific notation for relapse, I think it will be easier to have
T vs R and R vs T...
Or we can use 0 for normal, 1 for tumor, 2 for relapse... ?

**Comment by szilvajuhos** [comment]
We can reopen when it is really an issue.
