### ISSUE TITLE
Unify bianca and milou configuration

### ISSUE THREAD

**Issue by marcelm** [SciLifeLab/CAW#215]
This is the current diff between `configuration/milou.config` and `configuration/bianca.config`:
```
--- bianca.config       2017-03-20 16:18:49.656447658 +0100
+++ milou.config        2017-03-20 16:18:49.721844364 +0100
@@ -117,7 +117,7 @@
     memory = {params.singleCPUMem * 2 * task.attempt}
   }
   $RunAscat {
-    module = ['R/3.3.2']
+    module = ['R/3.2.3']
     cpus = 1
     memory = {params.singleCPUMem * 2 * task.attempt}
   }
```
Is this worth keeping two separate files?

**Comment by szilvajuhos** [comment]
No, but there is no 3.3.2 on bianca yet. In fact it is not working on bianca in general, so we can update to 3.3.2, ask UPPMAX to fix R packages and use a single common  UPPMAX config file.

**Comment by marcelm** [comment]
Has anyone been in contact with Uppmax support, yet?

**Comment by szilvajuhos** [comment]
Yes, but there were so many mails back and forth that it was lost in details. I can give an other shot again.

**Comment by szilvajuhos** [comment]
Looks R 3.3.2 and R_packages 3.3.2 are available by now on both bianca and irma, so we can use a single UPPMAX settings.

**Comment by marcelm** [comment]
Great! I’ll send a PR.
