### ISSUE TITLE
Is step a list or not?

### ISSUE THREAD

**Issue by marcelm** [SciLifeLab/CAW#224]
The `--step` parameter is parsed as a list:
```
step = params.step ? params.step.split(',').collect {it.trim()} : []
```
But then it is required to contain only a single value:
```
if (step.size() != 1) {exit 1, 'Please choose only one step, see --help for more information'}
```
Also the expression `"something" in step` is used quite often, treating it as a list again.

**Comment by MaxUlysse** [comment]
It's a list of one element. I was lazy... But I was planning to correct it.
