### ISSUE TITLE
Make the pipeline work with GRCh38

### ISSUE THREAD

**Issue by marcelm** [SciLifeLab/CAW#250]
Work on this has started. There are some remaining issues, which I would like to document here. (Possibly it makes sense to open separate issues.)

* [x] Figure out which "known indels" files we should use. For GRCh37, there is Mill’s and 1KG, but the GRCh38 bundle does not contain a VCF with 1KG indels. (*Update*: Broad uses Mill’s and a file named ` "Homo_sapiens_assembly38.known_indels.vcf.gz`)
* [x] Nearly all calls to GATK use the parameter `-XL` (`--excludeIntervals`) to exclude the two contigs hs37d5 and NC_007605. This is specific to GRCh37 and gives an error message on GRCh38.
* [x] The params.intervals setting is set to `centromeres.list` in GRCh37. A similar file exists in the GRCh38 bundle, but it has a different format. [File format for interval lists](https://software.broadinstitute.org/gatk/guide/article?id=1319)

Lower priority:
* [ ] For ASCAT and Cosmic, we need some GRCh-38-specific files. Relevant when the pipeline is actually going to be used on cancer samples.

See also [the workflow used at Broad](https://github.com/broadinstitute/wdl/tree/develop/scripts/broad_pipelines).

**Comment by marcelm** [comment]
See #261

**Comment by marcelm** [comment]
As soon as #261 is merged, I’m going to close this. I am myself not going to work on supporting GRCh38 for cancer samples as that is not part of my project. So I suggest to open a separate issue for the ASCAT and Cosmic GRCh38-specific things.

**Comment by szilvajuhos** [comment]
Not closing, only changing assignee. We have to go through with @malinlarsson how things should be changed for GRCh38, also we have to consider testing using Valtteri's data (negotiate with him and @vezzi ).

**Comment by marcelm** [comment]
Alright. I’m happy to continue helping with anything related to normal samples.

**Comment by marcelm** [comment]
Since issue is staring me in the face every time I look at the issue list, I am closing it now because the implementation is done and being used.

Please open a new issue for anything else related to GRCh38 that may need to be done.
