### ISSUE TITLE
Update Nextflow version ?

### ISSUE THREAD

**Issue by MaxUlysse** [SciLifeLab/CAW#268]
Nextflow 0.24 is up for some days.
There is some improvements with this version.
cf https://github.com/nextflow-io/nextflow/releases

**Comment by MaxUlysse** [comment]
I'd love to use the new `combine` and `collect` operators.
But I'm guessing we'll have to ask UPPMAX to update their version too.
And we'll break backwards compatibility.
What do you think?

**Comment by szilvajuhos** [comment]
Duplicate of #385 so closing.
