### ISSUE TITLE
--test is slow again

### ISSUE THREAD

**Issue by marcelm** [SciLifeLab/CAW#279]
... because this line was removed in commit 307e15cb5dfd422196444a5780182a99f1ff4640:
```
referenceMap.intervals = "$workflow.projectDir/repeats/tiny.list"
```

**Comment by MaxUlysse** [comment]
Yes I removed it and used the intervals made with the small reference.

**Comment by MaxUlysse** [comment]
And it's not working with smallGRCh37.
I'm trying to fix it ;-)
