### ISSUE TITLE
Do not explicitly create a base-quality recalibrated BAM

### ISSUE THREAD

**Issue by marcelm** [SciLifeLab/CAW#281]
See http://gatkforums.broadinstitute.org/gatk/discussion/comment/27076/#Comment_27076 .
The idea is to only create the recalibration table (with BaseRecalibrator), but to not produce the recalibrated BAM (which uses PrintReads and is extremely slow). Instead, the recalibration table can be passed as a parameter directly to HaplotypeCaller (or any other GATK tool), which applies the recalibration on-the-fly to the input BAM.

Since the pipeline is not going to deliver recalibrated BAM files anyway and all GATK tools support this, the recalibrated BAM file would only need to be generated if a non-GATK downstream tool needs recalibrated BAMs.

**Comment by marcelm** [comment]
This is a list of the tools are run on the recalibrated BAM, along with their support for the `--BQSR` option.

* `samtools stats`. Probably not.
* HaplotypeCaller. Yes.
* MuTect. Probably yes.
* MuTect2. Probably yes.
* FreeBayes. No, but FreeBayes does not need recalibrated qualities.
* VarDict. Probably not.
* Strelka. Probably not.
* Manta. Probably not.

**Comment by MaxUlysse** [comment]
I do think it's great idea.
We should skip recalibration for tools that don't require it.
That way if you run tools that don't need recalibration that's a costing process you can remove.

And if for a future run you do want to use tools that need recalibration, you can always restart from `--step recalibrate`.
