### ISSUE TITLE
singleCPUMem  set to 7.GB will allocate 2 cores on bianca

### ISSUE THREAD

**Issue by ansluk** [SciLifeLab/CAW#283]
singleCPUMem = 7.GB in uppmax-slurm.config will allocate two cores to single core jobs on bianca.
7.GB translates to "#SBATCH --mem 7168" in the slurm start scripts and the default MB per core is 7000.

singleCPUMem = 7000.MB allocates one core as expected.

Also the default memory directive for a full 16 core node fails.
memory = 110.GB has to be decreased to 112000.MB

**Comment by szilvajuhos** [comment]
The other thing I had to do on bianca when using the standard config (i.e. running jobs from a screen and launching nextflow from the shell) to get rid of the memory/cpu allocation lines of configuration/uppmax-slurm.config like:
```
process {
  executor = 'slurm'
  //cpus = 16
  //memory = 110.GB
  time = 999.h
  queue = 'node'
  clusterOptions = {"-A $params.project"}
....
```
My feeling is that both slurm and nextflow is trying to set the resources and it only makes a confusion.

How are you running your jobs, as a batch using /scratch (i.e. like CAW/scripts/runPreprocessingOnScratch.sh ) or directly from a command line, leaving job submission for nextflow?

**Comment by ansluk** [comment]
So far I'm running directly from command line using the standard profile with nextflow submitting jobs to slurm. When I commented out the memory directive like above previously, the main.nf script failed because task.memory was absent and to be used in java -Xmx${task.memory.toGiga()} when starting java.

**Comment by szilvajuhos** [comment]
Could you please copy/send me a command line you are using, so I can try something similar?

**Comment by szilvajuhos** [comment]
@ansluk  I am closing this as @marcelm started to work on #342 . Hoping once the config files are cleaned up, we can have a better view what is going on. 
Generally, looks slurm on UPPMAX clusters looks only at the CPU allocation. If we want to have 32Gs for a process when 8G is allocated for each core, we have to add 4 CPUs even if only one is used. Furthermore, bianca nodes have ~104G althogether, therefore, each core has 6.5G allocated. So, to get 32Gs, we have to add 5 cores at least.
