### ISSUE TITLE
Make RunHaplotypecaller faster by running large jobs first

### ISSUE THREAD

**Issue by marcelm** [SciLifeLab/CAW#292]
The HaplotypeCaller jobs are split into separate jobs using a list of intervals that omit centromeric regions (`wgs_calling_regions_CAW.list` on GRCh37). The list of intervals should be sorted such that large intervals are processed first. This increases the degree of parallelism. Otherwise, the pipeline may end up waiting for a large interval that was started late.

This is particularly severe for GRCh38 where the interval list defines many intervals of highly varying size.

**Comment by szilvajuhos** [comment]
If we are feeding the intervals into a channel, and jobs are submitted from the channel, the order is usually random. I guess there is a hash in the background, but whatever: sorting the input interval file is not enough.

**Comment by marcelm** [comment]
Hm, but isn’t it guaranteed that values come out of a channel in the same order you put them in? Then I would assume that the processes are also launched in that order. On the other hand, I agree it’s random when the processes *finish*. I think just ordering the intervals would do the right thing!

**Comment by marcelm** [comment]
Ok, I see where this could happen: There is a step in the pipeline where the Channels for the tumor and normal samples are "mixed" (`.mix`). The `.mix` operator does not guarantee how it mixes the two channels, so it could happen that all the intervals on the tumor samples get run first and then all the intervals on the normal samples. We can fix this, at least partially, by using `.merge` instead (but that seems to be not in the Nextflow version we are using).

**Comment by marcelm** [comment]
I tested this now. When sorting the intervals, these messages:

    Submitted process > RunHaplotypecaller (...-chr7_62506780-143650804)

appear not precisely in the order of decreasing interval size, but it seems that this is only because the message is printed after the processes are launched (which takes a little bit of time). However, if we have n cores, then actually the n first launched processes will work on the n largest intervals, which is all we need.

**Comment by szilvajuhos** [comment]
Shall I test it, or can I close as ready?

**Comment by marcelm** [comment]
I tested this. There is some improvement, but it isn’t so great because the interval size does not correlate well to processing time. I’d like to re-order the intervals according to actual processing time using the one dataset that I ran.

**Comment by szilvajuhos** [comment]
The other thing I have realised that the coordinates are pretty vague. There are few Kb centromeric regions that are already repeats and we are doing variant calling on them. Looks like a minor issue, but it can be annoying to wait 2 days to complete 10Kb for deep coverage data.

**Comment by marcelm** [comment]
Ok, I’ll send in a PR soon, but here are some runtimes (on a GRCh38 test data set), just to have this written somewhere:

* Current sort order: 8h 11min
* Sorting by interval length: 8h 4min (this is probably not even significant)
* "Hand-sort" by runtime derived from the previous run: 7h 20min.

So this is a 10% reduction - not extremely helpful, but better than nothing.
