### ISSUE TITLE
Improve ConcatVCF efficiency

### ISSUE THREAD

**Issue by marcelm** [SciLifeLab/CAW#305]
About 30% of variant calling is spent in ConcatVCF, which uses Picard’s SortVcf at the moment. However, the individual files are already sorted, so we could just concatenate them in the correct order.

**Comment by marcelm** [comment]
The `awk` part of `ConcatVCF` takes 56 minutes on a GRCh38 test dataset. Total time is 3h 48min with the improvement in PR #304.

**Comment by szilvajuhos** [comment]
#304 resolved
