### ISSUE TITLE
Change annotation tools process

### ISSUE THREAD

**Issue by MaxUlysse** [SciLifeLab/CAW#317]
At the moment, we only run annotation tools conjointly with variant callers.
It could be good to run annotation tools in another run.
But we would need to restart variant callers.
The way I see it, we can something like:
- `vcfsForAnnotation = Channel.fromPath( 'VariantCalling/{MuTect1,MuTect2,Strelka}/*' )` and then run selected tools on these vcfs.
- specify a vcf or list of vcf via command line and run the selected tools on these vcfs.
- specify a tool and fetch the vcfs from the `VariantCalling` directory
- don't do anything

Which ideas do you like?
Do you have any others?

**Comment by szilvajuhos** [comment]
VCFs to annotate:

- Strelka: \*passed_somatic\*vcf
- MuTect2:
- MuTect1: only PASS variants
- Manta: \*somaticSV.vcf \*diploidSV.vcf
- FreeBayes: leave it for now

**Comment by MaxUlysse** [comment]
Should I pigz the vcf from Strelka too ?

**Comment by szilvajuhos** [comment]
Those are really small VCFs. MuTect1 and FreeBayes VCFs are large, HaplotyeCaller gVCF is huge.

**Comment by MaxUlysse** [comment]
In fact, we are unzippinng Manta vcf, and just Strelka is not gzip in the end.
The idea is just to get all the files in the same format in the end.
