### ISSUE TITLE
Strelka?

### ISSUE THREAD

**Issue by MaxUlysse** [SciLifeLab/CAW#352]
We have some troubles with Strelka:
```
INFO: Scanning reference genome
ERROR: BAM headers and reference fasta disagree on chromosome: 'HLA-A*01'
at [strelkapath]/lib/Utils.pm line 44.
Utils::errorX('BAM headers and reference fasta disagree on chromosome: \'HLA...') called at [strelkapath]/bin/configureStrelkaWorkflow.pl line 348
[samplepath]/VCtest/Strelka/work/f2/449eaaca699612fbf6ba007597c407/.command.run.1: line 90: 23332 Terminated              nxf_trace "$pid" .command.trace
```

We are currently using the latest UPPMAX available module version wich is 1.0.15.
Illumina took over Strelka development: https://github.com/Illumina/strelka
I do think it's a good idea to update our Strelka version to 2.7.1 (and ask UPPMAX to do the same).

What do you think ?

**Comment by szilvajuhos** [comment]
https://groups.google.com/forum/#!topic/strelka-discuss/sQvXiuS6Q18
