### ISSUE TITLE
Rename steps

### ISSUE THREAD

**Issue by marcelm** [SciLifeLab/CAW#356]
As discussed on Slack, we could rename two of the steps:

* `skippreprocessing` → `variantcalling`
* `preprocessing` → `mapping`

The semantics should also be made a bit clearer: The `--step` gives the step at which the pipeline *starts*.

**Comment by MaxUlysse** [comment]
I think it's a great idea

**Comment by MaxUlysse** [comment]
But I think that if we do that we're breaking retro-compatibility, and need to move forward 1.2
