### ISSUE TITLE
Create Ascat loci file for GRCh38

### ISSUE THREAD

**Issue by malinlarsson** [SciLifeLab/CAW#357]
I have started this but need to test it before uploading.

**Comment by malinlarsson** [comment]
I have created a new loci file for Ascat in GRCh38 coordinates. I used liftOver at the UCSC genome browser to just convert the coordinates in the GRCh37 loci file. Most SNPs were successfully converted, about 6000 out of ~3200000 failed and that should not have a big impact on the Ascat results. 
The new loci file for GRCh38 is temporarily stored in /sw/data/uppnex/ToolBox/ReferenceAssemblies/hg38make/bundle/2.8/1000G_phase3_GRCh38_maf0.3.loci
It would be great if someone with write permission to /sw/data/uppnex/ToolBox/hg38bundle could move it there. @marcelm could you move the file there?
Also perhaps it should be included in the web export @MaxUlysse? Could you do that?

I have updated the documentation about Ascat, but it has to be updated again when the loci file is in place in /sw/data/uppnex/ToolBox/hg38bundle.

**Comment by szilvajuhos** [comment]
@malinlarsson it is read-only, could you please make it chmod 644 at least please?

**Comment by malinlarsson** [comment]
Ascat as it is now (in /bin/ascat.r) doesn't work if the chromosome name has "chr" in it. The chromosomes are hard coded in this file to chrs = c(1:22,“X”,“Y”). 
To use Ascat with the LogR and BAF files that are currently generated we need to remove the "chr" in chromsome names. Could be done like this: 
sed 's/chr//g' idsamplenormal.BAF > idsamplenormal_new.BAF
sed 's/chr//g' idsamplenormal.LogR > idsamplenormal_new.LogR
sed 's/chr//g' idsampletumor.BAF > idsampletumor_new.BAF
sed 's/chr//g' idsampletumor.LogR > idsampletumor_new.LogR
and then feed in the new files to run_ascat.r

**Comment by ewels** [comment]
This is now done! 🎉
