### ISSUE TITLE
Delivering all the reads

### ISSUE THREAD

**Issue by szilvajuhos** [SciLifeLab/CAW#387]
The realigned BAM files stored in the Preprocessing/NonRecalibrated directory are not containing all the reads that are in the initial FASTQ files. We have to make sure all the reads are in these files as these are delivered to the users.

**Comment by szilvajuhos** [comment]
- [x] All the reads are represented at least twice in the normal MD BAM
- [ ] All the reads are represented at least twice in the tumour MD BAM
- [ ] All the reads that are in the normal FASTQ are also in the MD BAM
- [ ] All the reads that are in the tumour FASTQ are also in the MD BAM

We are checking counts by something like
`samtools view NonRealigned/B-3004_0.md.bam|awk '{print $1}' | sort | uniq -c |awk '{if($1<2){print}}'`

**Comment by szilvajuhos** [comment]
```szilva@irma2:~/PI-1218/CAW/3004/Preprocessing $ md5sum *uniq
ecbeb0477484c3039df4fbfdda495674  B-3004.fastq.reads.uniq
ecbeb0477484c3039df4fbfdda495674  B-3004.md.reads.uniq
f37f6bac0fb26bb89b6461c80bc15ce2  T-3004.fastq.reads.uniq
f37f6bac0fb26bb89b6461c80bc15ce2  T-3004.md.reads.uniq
```

**Comment by szilvajuhos** [comment]
- [x] we are not loosing reads at IndelRealigner
- [ ] remove -L from CreateRecalibrationTable 
- [ ] remove -L from BaseRecalibrator (why were there at first place?)
- [ ] add test dummy reads not aligning to anywhere

**Comment by MaxUlysse** [comment]
Is this fix ?

**Comment by szilvajuhos** [comment]
Yep, at least the tests were ok.

**Comment by MaxUlysse** [comment]
OK, shall we close this issue then?
