### ISSUE TITLE
Problem with Ascat and R-version on Milou

### ISSUE THREAD

**Issue by malinlarsson** [SciLifeLab/CAW#388]
I got a new error in Ascat after downloading the latest CAW (I downloaded it 22 days ago, the latest commit in my version is afcc359 @marcelm marcelm Fix ConcatVCF on GRCh37. I hope this is enough information). 

The error occurs in RunAscat.

Here is the **.command.log** file in the work directory of this process: 
[malin@milou2 aa886ddee40bf3136ab5f67f139dea]$ more .command.log 

The following have been reloaded with a version change:
  1) java/sun_jdk1.7.0_25 => java/sun_jdk1.8.0_92

Lmod has detected the following error: Cannot load module "R_packages/3.4.0" because these modules are loaded:
  R

Here is the **.command.env** file from the same work directory:
[malin@milou2 aa886ddee40bf3136ab5f67f139dea]$ more .command.env 
nxf_module_load(){
  local mod=$1
  local ver=${2:-}
  local new_module="$mod"; [[ $ver ]] && new_module+="/$ver"

  if [[ ! $(module list 2>&1 | grep -o "$new_module") ]]; then
    old_module=$(module list 2>&1 | grep -Eo "$mod\/[^\( \n]+" || true)
    if [[ $ver && $old_module ]]; then
      module switch $old_module $new_module
    else
      module load $new_module
    fi
  fi
}

nxf_module_load R 3.3.2
nxf_module_load R_packages
export NXF_OPTS="-Xms1g -Xmx4g"
export PATH="/proj/b2011185/nobackup/private/analysis/CAW/CAW/bin:$PATH"

Seems to be a clash between R-versions?

**Comment by MaxUlysse** [comment]
I'm looking into it, I think there is indeed a clash between 2 R modules.

**Comment by malinlarsson** [comment]
Hi, I'm back on this error now (after vacation). 
I think we should separate this error from trying to update Ascat to 2.5, to avoid introducing new errors into CAW in the update process. Better to have one functioning module first. 
Also, not sure if the update is needed for us (see comment in #407).

**Comment by MaxUlysse** [comment]
You're the ASCAT expert ;-)

**Comment by malinlarsson** [comment]
Hello, I've finally had some time to look at the Ascat error on Milou.
 
I noted in CAW/configuration/uppmax-modules.config we have this code for Ascat:
$RunAscat {
    module = ['R/3.3.2','R_packages']
  }
Is there a reason for including the module 'R_packages'?

I noted that if I manually load 'R/3.3.2' I can not load 'R_packages':
```
[malin@milou2 WNB125]$ module load R/3.3.2

The following have been reloaded with a version change:
  1) java/sun_jdk1.7.0_25 => java/sun_jdk1.8.0_92

[malin@milou2 WNB125]$ module list

Currently Loaded Modules:
  1) uppmax          3) Nextflow/0.22.2   5) gcc/6.2.0              7) libcurl/7.45.0   9) bzip2/1.0.6  11) pcre/8.38
  2) bioinfo-tools   4) R/3.3.2           6) java/sun_jdk1.8.0_92   8) zlib/1.2.8      10) xz/5.2.2
[malin@milou2 WNB125]$ module load R_packages

Lmod has detected the following error: Cannot load module "R_packages/3.4.0" because these modules are loaded:
  R
```

When I unloaded 'R/3.3.2' I could load 'R_packages', which appear to load 'R/3.4.0':
```[malin@milou2 WNB125]$ module unload R/3.3.2
[malin@milou2 WNB125]$ module load R_packages
[malin@milou2 WNB125]$ module list

Currently Loaded Modules:
  1) uppmax            4) R_packages/3.4.0   7) java/sun_jdk1.8.0_92  10) zlib/1.2.8   13) cairo/1.14.8
  2) bioinfo-tools     5) R/3.4.0            8) libcurl/7.45.0        11) bzip2/1.0.6  14) texinfo/6.0
  3) Nextflow/0.22.2   6) gcc/6.2.0          9) pcre/8.40             12) xz/5.2.2     15) texlive/2016
```

R/3.4.0 does not have RColorBrewer installed, and therefore Ascat does not work. 

When I manually loaded R/3.3.2 and then manually run the script CAW/bin/run_ascat.r it worked on Milou, and the plots were generated. 

I will try to remove the module 'R_packages' and se if it helps.
