### ISSUE TITLE
Reports should always be created

### ISSUE THREAD

**Issue by marcelm** [SciLifeLab/CAW#390]
I’d like to suggest that `--reports` becomes the default. A new command-line option `--no-reports` could be added to disable creation of reports.

Reasons:
* It is hard to get the reports afterwards on an already finished dataset if you have forgotten to add `--reports`
* Reports are usually needed
* Reports are easy to compute (not sure if that is true - I haven’t measured it)

**Comment by MaxUlysse** [comment]
That's very smart, I should have done that from the beginning.
And I do think that the time needed for making reports are nothing compared to preprocessing/variant calling.
I'll look into it.
