### ISSUE TITLE
Index output VCFs with tabix

### ISSUE THREAD

**Issue by marcelm** [SciLifeLab/CAW#391]
We should tabix-index the VCFs that the pipeline creates.

For that, we need to compress the output VCFs with `bgzip` instead of regular `gzip`. That also means unfortunately that we cannot use `pigz` in the ConcatVCF step anymore. Possibly use https://github.com/nh13/pbgzip instead.

**Comment by MaxUlysse** [comment]
I have no problem removing pigz and trying another tool for parallel gziping, and if we do have tabix indexes, it would be a good thing.
I'll look into it too.
Thanks for all the idea ;-)

**Comment by marcelm** [comment]
Thanks, and sorry I don’t have time to do this myself right now.

**Comment by marcelm** [comment]
I just noted that recent versions of the standard `bgzip` also have an option to use multiple threads. we would just need to use `bgzip -@ 16`. It is not as fast as `pbgzip` unfortunately, see chapmanb/bcbio-nextgen#1278.
