### ISSUE TITLE
Installation link in the README is broken

### ISSUE THREAD

**Issue by pditommaso** [SciLifeLab/CAW#392]
The link "installation documentation" in the readme file does not load.

**Comment by MaxUlysse** [comment]
Thanks a lot for catching that.
I'll correct it first thing in the morning ;-)

**Comment by pditommaso** [comment]
The link in the third paragraph `See the installation documentation for more information` is still broken. #documentationreview ;)

**Comment by MaxUlysse** [comment]
My bad, 3 other links to the installation documentation were broken too...
