### ISSUE TITLE
TM data tests

### ISSUE THREAD

**Issue by szilvajuhos** [SciLifeLab/CAW#43]

**Comment by malinlarsson** [comment]
Preprocessing has been tested on one "real" WGS sample with 60 x coverage in tumor and 30x coverage in normal. Testing was done on Milou. The preprocessing took approximately  107 hours on Milou when I used the -t = 240:00:00 setting under "clusterOptions"

**Comment by szilvajuhos** [comment]
@malinlarsson I guess it is an ongoing thing, I will close it as not related to actual CAW code
