### ISSUE TITLE
Run FastQC after Mapping

### ISSUE THREAD

**Issue by MaxUlysse** [SciLifeLab/CAW#481]
cf #439 
I think we can do that easily if we branch the RunFastQC process after MapReads process.

**Comment by marcelm** [comment]
This conflicts with #459

**Comment by MaxUlysse** [comment]
Yes, sorry, I forgot about this future improvement ;-)
I'll try to make it work after we merge #459 then.
I just had the idea when looking for something else, and though I give it a try.
