### ISSUE TITLE
grch38 coordinates in cosmic vcf for grch37

### ISSUE THREAD

**Issue by ansluk** [SciLifeLab/CAW#494]
The contig part of the vcf header in the vcf-file on uppmax with cosmic data for grch37 looks like grch37 but the actual coordinates of the variations are grch38.

 (/sw/data/uppnex/ToolBox/ReferenceAssemblies/hg38make/bundle/2.8/b37/b37_cosmic_v74.noCHR.sort.4.1.vcf)

**Comment by szilvajuhos** [comment]
Bugger, thanks, will fix ASAP, have to find somebody to change permissions first.

**Comment by szilvajuhos** [comment]
You can add /sw/data/uppnex/ToolBox/ReferenceAssemblies/hg38make/bundle/2.8/b37/GRCh37_Cosmic_v83.vcf to your genomes.config file, also sent a PR in the main branch
