### ISSUE TITLE
bianca instructions minor issues

### ISSUE THREAD

**Issue by Netzach** [SciLifeLab/CAW#515]
The script calling _./scripts/do_all --pull_ should be _./scripts/do_all.sh --pull_
Also, there are no instructions telling you to have _nextflow_ installed or loaded, which is necessary for creating the singularity images.

**Comment by MaxUlysse** [comment]
Thanks a lot for the input.
I will clarify the instructions ASAP.

**Comment by MaxUlysse** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [bianca instructions minor issues](https://trello.com/c/BpE8U0NU/51-bianca-instructions-minor-issues)
