### ISSUE TITLE
Validate preprocessed bam files

### ISSUE THREAD

**Issue by malinlarsson** [SciLifeLab/CAW#71]

**Comment by malinlarsson** [comment]
Validate that the generated recalibrate bam files for real WGS samples are ok. 
Plan: Use samtools idxstats and compare with previously generated files for the same sample.

**Comment by malinlarsson** [comment]
I think I have verified that the .bam files generated with Preprocessing are OK. 

I have used samtools idxstats to check how many reads were mapped (and unmapped) to the chromosomes/contigs in hg19. 
I have compared the bam files after Mark duplicates, indel realaignment and base quality score recalibration. 
Every contig has exactly the same number of mappped and unmapped reads after each step. 
I have not tested the original bam files because there are no .bai files corresponding to the inital bam files. (Could be generated if we want to be really careful). 

I have also compared the results with samtools idxstats on the final bam file generated previously by “my pipeline”. It contains exactly the same steps, but I did the mapping against human_g1k_v37.fasta without the decoys sequences. 
There were some small differences that probably has to do with the change in reference assembly.

**Comment by szilvajuhos** [comment]
So, it should be all right, and we could feed it into the rest of the pipeline. Have to make a TSV file that corresponds to the preprocessed BAM waiting for recalibration, its index and the recalibration table. And start with --steps nopreprocessing,....
