### ISSUE TITLE
Use GATK 3.6 only

### ISSUE THREAD

**Issue by szilvajuhos** [SciLifeLab/CAW#72]
Now we are using different versions for calibration/realignment and for variant call (HaplotypeCaller and MuTect2) . The v3.6 jar should contain all these tools, we should use only that and the variabla gatkHome (not mutect2Home)

**Comment by MaxUlysse** [comment]
Done.
Just trying to see if the results are similar..

**Comment by MaxUlysse** [comment]
```
samtools idxstats old.bam > old.stats
samtools idxstats new.bam > new.stats
sdiff -s old.stats new.stats
```
`hs37d5  35477943        81      1                             | hs37d5  35477943        0       0`

> That looks good, as this contig is ignored in the recent versions

**Comment by MaxUlysse** [comment]
```samtools idxstats tiny-new.normal__0.recal.bam > tiny-new.normal.stats
samtools idxstats tiny-new.tumor__1.recal.bam > tiny-new.tumor.stats
samtools idxstats tiny-old.normal__0.recal.bam > tiny-old.normal.stats
samtools idxstats tiny-old.tumor__1.recal.bam > tiny-old.tumor.stats

sdiff -s tiny-old.normal.stats tiny-new.normal.stats
sdiff -s tiny-old.tumor.stats tiny-new.tumor.stats```

No differences, except the hs37d5 contig

**Comment by MaxUlysse** [comment]
I compared the two normal samples on IGV, and didn't find any differences.
