### ISSUE TITLE
Remove hard-coded parameters

### ISSUE THREAD

**Issue by silverdaz** [SciLifeLab/CAW#81]
Reporting some issues I've had with the workflow.

First: Line 1086 of `MultiFQtoVC.nf` should probably be erased.
https://github.com/SciLifeLab/CAW/blob/master/MultiFQtoVC.nf#L1086

Then, would it be possible to make all the
```
    cpus 8
    memory { 16.GB * task.attempt }
    time { 20.h * task.attempt }
    errorStrategy { task.exitStatus == 143 ? 'retry' : 'terminate' }
    maxRetries 3
    maxErrors '-1'
```
for example: https://github.com/SciLifeLab/CAW/blob/master/MultiFQtoVC.nf#L324-L329
and update it to a `nodeSetup()` function, or so?

So that it is not hard-coded.

Or something like
```
    cpus $nodeCPUs
    memory { $nodeRAM * task.attempt }
    time { $nodeTimeSlice * task.attempt }
    errorStrategy { task.exitStatus == 143 ? 'retry' : 'terminate' }
    maxRetries 3
    maxErrors '-1'
```

**Comment by MaxUlysse** [comment]
Thanks for the idea with the configuration of each process memory and CPU.
I'm looking into it

The Strelka typo is corrected.

**Comment by MaxUlysse** [comment]
Duplicate #79
