### ISSUE TITLE
DREAM Challenge runs

### ISSUE THREAD

**Issue by szilvajuhos** [SciLifeLab/CAW#98]
These runs are to get results from Strelka and MuTect1 from all the DREAM datasets

**Comment by szilvajuhos** [comment]
See progress in Google sheet
https://docs.google.com/a/scilifelab.se/spreadsheets/d/1INb62-tgX_W6p8R59HsywsYOcfEO857Tjo8uQDY3u3g/edit?usp=sharing

**Comment by szilvajuhos** [comment]
For S0 and S1 the MuTect1 and Strelka runs are OK. Fixed Manta, so will restart pending Manta runs.
The good thing is that Manta also gives a list of small indels, so we will have more information about them, not only the single list of indels from Strelka.

**Comment by MaxUlysse** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Run DREAM Challenge](https://trello.com/c/9Nxhg2fS/34-run-dream-challenge)

**Comment by szilvajuhos** [comment]
Done
